circleci: use a patched opam.rb
The current one gives the following error:

    Error: opam: "cxx11" is not a recognized standard

I cargo culted this change from https://github.com/moby/vpnkit/commit/4bb313b0d76fccc508299133e36c2c015184eec8

Signed-off-by: Ian Campbell <ijc@docker.com>